- hosts: app_servers
  become: yes
  tasks:
    - name: Update apt cache
      apt: update_cache=yes cache_valid_time=3600

    - name: Install Python & pip
      apt: name={{ item }} state=present
      loop:
        - python3
        - python3-pip
        - git

    - name: Copy app code
      copy:
        src: ../app/
        dest: /opt/app
        owner: ubuntu
        group: ubuntu
        mode: 0755

    - name: Install requirements
      pip:
        requirements: /opt/app/requirements.txt
